### ISSUE TITLE
Create governance model and document it

### ISSUE THREAD

**Issue by kpfleming** [bqplot/governance#3]
This project is now independent, and as a result will need a documented governance process. This issue is the place to discuss that.

**Comment by jasongrout** [comment]
Moving issue to the governance repo as a more appropriate place for these notes.

During the 11 Jun 2020 meeting, Kaia, Chakri, Sylvain, and I worked on the code of conduct enforcement manual.

**Comment by jasongrout** [comment]
During the 18 June 2020meeting, Kaia, Chakri, Sylvain, and Itay worked through the rest of the code of conduct enforcement.

@SylvainCorlay will be doing some work in the coming week to set up email lists, etc. The big item of business for next week is appointing a steering council and making plans for the NumFOCUS application.

**Comment by jasongrout** [comment]
It sounds like this can be closed, now that the transition team has completed its work and the new steering council is active.

Also, this repo's description in github still says "in-progress draft" - that can probably be changed to something more official.

**Comment by SylvainCorlay** [comment]
Good catch. Removing the "in-progress" and closing.
